exports.usersRoute = require('./users')
exports.alertsRoute = require('/alerts')
exports.categoriesRoute = require('./categories')
exports.contract_typesRoute = require('./contract_types')
exports.hourly_typesRoute = require('./hourly_types')
exports.measurement_unitsRoute = require('./measurement_units')
exports.meetingsRoute = require('./meetings')
